### ISSUE TITLE
Error message in Front Page (default install)

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/glance_ynh#4]
`unexpected status code 403 for https://www.reddit.com/r/yunohost/hot.json?, response: <body class=theme-beta><div><style>.theme-light,:root{--rem360:22.5rem;--rem320:20rem;--rem192:12rem;--rem144:9rem;--rem128:8rem;--rem96:6rem;--rem90:5.625rem;--rem88:5.5rem;--rem64:4rem;--rem56:3.5rem;--rem48:3rem;--rem40:2.5rem;--rem36:2.25rem;--rem32:2r`

![yunohost 2024-05-26 at 11-52-43 Home - Glance](https://github.com/YunoHost-Apps/glance_ynh/assets/365281/1331a993-2e99-41d5-b848-a8b2a93698e5)

**Comment by ericgaspar** [comment]
I removed the reddit widget from default settings in `glance.yml` (I think reddit is restricting acces to his API...).

**Comment by bugsysop** [comment]
From the doc:

>Warning
>Reddit does not allow unauthorized API access from VPS IPs, if you're hosting Glance on a VPS you will get a 403 response. As a workaround you can route the traffic from Glance through a VPN or your own HTTP proxy using the request-url-template property.

Note: my instance of YNH is on a VPS
